# -*- coding: utf-8 -*-
"""Scientific Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KJ7b9jZU2foHPG9z0V7QmwZmexwmzYDo
"""

def get_one_num(): #defining input for operations that require one number
  num1= float(input("Enter the first number"))
  return num1

def get_two_num(): #defining input for operations that require two numbers
  num1= float(input("Enter the first number"))
  num2= float(input("Enter the second number"))
  return num1, num2

import math
operation = input("Enter the operation(+,-,*,/,%,sqrt,**,sin,cos,tan,log,abs),")
if (operation == "+"):
  num1, num2 = get_two_num()
  print(num1+num2)
elif(operation =="-"):
  num1, num2 = get_two_num()
  print(num1-num2)
elif(operation =="*"):
  num1, num2 = get_two_num()
  print(num1*num2)
elif(operation == "/"):
  num1, num2 = get_two_num()
  if (num2 == 0):
    print("Cannot divide by zero")# Dividing by 0 would lead to infinity
  else:
    print(num1/num2)
elif(operation =="%"):
  num1, num2 = get_two_num()
  print(num1%num2)
elif(operation =="sqrt"):
  num1 = get_one_num()
  print(math.sqrt(num1))
elif(operation =="**"):
  num1, num2 = get_two_num()
  print(num1**num2)
elif(operation=="sin"):
  num1 = get_one_num()
  print(math.sin(math.radians(num1)))#math.radians is a build in python function that converts radians to degrees.
elif(operation=="cos"):
  num1 = get_one_num()
  print(math.cos(math.radians(num1)))
elif(operation=="tan"):
  num1 = get_one_num()
  print(math.tan(math.radians(num1)))
elif(operation=="log"):
  num1 = get_one_num()
  print(math.log(num1))
elif(operation=="abs"):
  num1 = get_one_num()
  print(abs(num1))
else:
  print("Invalid operation")

